title: 幻雪之地
description: 我的个人博客
author: fish/snowwolfjay/余红杰
logo: /static/img/avatar.png
github: https://github.com/snowwolfjay
about: 一名js爱好者——a js lover

baseurl: "https://snowwolfjay.github.io"
url: "https://snowwolfjay.github.io"

allowsearch: true

disqus_shortname: yuhj
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
